### ISSUE TITLE
Calling processIcons() second time causing uncaught exception

### ISSUE THREAD

**Issue by keblodev** [josejuanqm/JQSwiftIcon#2]
Having this in your dynamic view is going to crash your app on second time you load your view:

```
    override func viewDidLoad() {
        super.viewDidLoad()

        mySweetIconLabel.processIcons()
    }
```

*Tested with current version on cocoapods
TODO: test with fork from git src

**Comment by keblodev** [comment]
confirmed with current version from src. Gonna prepare fix and refactoring in PR

**Comment by josejuanqm** [comment]
could you share a demo?

Thanks for the feedback!

**Comment by keblodev** [comment]
Hey!
The problem was with Material Icons font **NAME** -> the case when font name is different from fileName is not counted currently in your code, and material icons font is written like this "Material Icons", so when this check is being performed 

```
 if (UIFont.fontNamesForFamilyName(fontName).count == 0) {...}
```

fontName passed there is actually "MaterialIcons-Regular" which is not equal to "Material Icons" and that forces FontLoader to load same font that is already loaded which throws an exception

Was busy this weekend to prepare PR, but will definitely do that this weekend.
And thanks for your work :)
